### ISSUE TITLE
What are these values?

### ISSUE THREAD

**Issue by jpw1991** [CW-Jesse/valheim-betterfps#2]
Hi Jesse,

I'm just curious about the meaning behind the values on lines 63, 69, and 74.

https://github.com/CW-Jesse/valheim-betterfps/blob/66e27b1f4a1137303328512c3d710a01bb9de748/CWJesse.BetterFPS/BetterFps_Patch_ThreadedAnimations.cs#L63

**Comment by CW-Jesse** [comment]
They're a salt for the hash. "But why?" I don't know. But they're there in the original code, so I have to copy them for the code to work. If I wasn't in such a hurry, I would've put them in a const called "hash" as they were in the original code before the compiler disassociated the number from its meaning for efficiency's sake.
